name: billion-air-flow
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel # -omit-info; for Jupyter
  - pandas
  - polars
  - dask
  - pyarrow
  - matplotlib
  - seaborn
  - jupyterlab # -omit-info; for Jupyter
  - duckdb
  - gputil # -import-name GPUtil
